baseURL = "/"
footnoteReturnLinkContents = "↩"
title = "HKL's Notes"
paginate = 10
theme = "lighthouse100-theme"

[params]
  AuthorName = "Kunlun HUANG"
  GitHubUser = "kunlunh"
  SidebarRecentLimit = 5
  Subtitle = "Just record things."
  Comments = "Cares"
  homepageurl = "https://xou.com/"
  IssueURL = "https://github.com/kunlunh/kunlunh.github.io/issues"
  LinkedinUser = "huangkunlun"
  CVurl = "https://hkl.ac.cn"

[permalinks]
  post = "/:year/:month/:slug/"
  pages = "/page/:filename"

